version: 2
updates:
  # For Gradle dependencies (including version catalogs)
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"  # Can be "daily", "weekly", or "monthly"
      time: "02:00"      # Run at 2 AM UTC
    open-pull-requests-limit: 5
    groups:
      # Group minor and patch updates together
      android-dependencies:
        patterns:
          - "androidx.*"
          - "com.android.*"
          - "com.google.*"
          - "io.*"
          - "org.*"
      testing-dependencies:
        patterns:
          - "androidx.*"
          - "de.mannodermaus.*"
          - "org.junit.*"
          - "io.mockk"
          - "com.willowtreeapps.assertk"
          - "app.cash.turbine"
      detekt:
        patterns:
          - "io.gitlab.arturbosch.detekt"

  # For GitHub Actions (bonus!)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"